/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ATUL' at '11/7/19 11:57 AM' with Gradle 3.0
 *
 * @author ATUL, @date 11/7/19 11:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
